### PR TITLE
Fix getattr uses with invalid default values

### PR DESCRIPTION
**Pull request by peterbell10**
If the lambdas return None here, then `split` or `decode` will raise, e.g.
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'

```

### CODE REVIEW

**Review by jeremiedbb — APPROVED** [review]
LGTM, thanks @peterbell10 !

**Comment by jeremiedbb** [comment]
could you add an entry in the change log ?

**Comment by peterbell10** [comment]
Added a small note to the changelog.

**Comment by jeremiedbb** [comment]
thanks @peterbell10 !

**Pull request merged**
