### PR TITLE
Fix typo in get_threading_layer

### PR DESCRIPTION
**Pull request by ogrisel**
I made a typo in #91, I am too tired...

### CODE REVIEW

**Comment by ogrisel** [comment]
We don't have tests for this.

**Comment by jeremiedbb** [comment]
It's not that easy to test since we don't build openblas (we build blis) and it can't be changed at runtime (like mkl) so it would be hard to find which threading_layer we expect to find unless we introspect the env to find how it was installed and maintain which packager ships openblas with which threading layer (although it might always be pthreads but not sure about that).

**Comment by ogrisel** [comment]
We could have a smoke test that only checks that the output belongs to a list of valid possible results.

**Comment by jeremiedbb** [comment]
Ok I'll try to come up with something

**Pull request merged**
